### ISSUE TITLE
Make reminders global

### ISSUE THREAD

**Issue by DigitalTech518** [DigitalTech518/Digibot#33]
Bug
Fix reminders, and make it global, so d!reminders can be used in any server, plus in dms for private reminders. Also make it so a member can only view the reminders they have, not someone else's.

**Comment by GreenDiscord** [comment]
This issue has been fixed as off 23:41 GMT, the owner forgot to set a string!

**Comment by DigitalTech518** [comment]
Haha this issue wasn't related to that, it was related to the fact that i made reminders **per guild**, that one string thing was just a mistake that i havent even set to an issue here
